version: 6.12.0.{build}
image: Visual Studio 2015

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

before_build:
- dotnet restore

build_script:
- ps: >-
    dotnet build -c Debug src\Stripe
    dotnet build -c Release src\Stripe

after_build:
- dotnet pack -c Release src\Stripe

artifacts:
- path: '**\*.nupkg'
