version: 6.10.0.{build}
image: Visual Studio 2015
configuration: Release

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: '6.10.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: ECHO [stripe.net]  Restoring Stripe.net's dependency (Json.NET), and Stripe.Tests dependency (Machine.Specifications)
- cmd: nuget restore src\Stripe.sln
- cmd: ECHO [stripe.net]  Finished with dependencies. Building Stripe.net and Stripe.Tests ...

build:
  project: src\Stripe.sln
  verbosity: quiet

after_build:
- cmd: ECHO [stripe.net]  Completed building Stripe.net and Stripe.Tests!

before_test:
- cmd: ECHO [stripe.net]  Running Stripe.net's Tests ...

artifacts:
- path: build
- path: src
- path: '**'
  name: Stripe.net

deploy:
  provider: NuGet
  api_key:
    secure: thisLLNeverWork!==
  verbosity: minimal
  artifact: /.*\.nupkg/
