version: 6.10.0.{build}
image: Visual Studio 2015
configuration: Release

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: '6.10.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore src\Stripe.sln

build:
  project: src\Stripe.sln
  verbosity: quiet

artifacts:
- path: build

on_success:
  - ps: |
  if ($true)
  {
    Write-Host "Test"
  }

deploy:
  provider: NuGet
  api_key:
    secure: thisLLNeverWork!==
  verbosity: minimal
  artifact: /.*\.nupkg/
