version: 6.10.0.{build}
stripe_net_version: 6.10.0
image: Visual Studio 2015
configuration: Release

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: '{stripe_net_version}'
  assembly_file_version: '{stripe_net_version}'
  assembly_informational_version: '{stripe_net_version}'

install:
- ps: Import-Module .\build\build.psm1

before_build:
- nuget restore src\Stripe.sln

build_script:
- ps: Invoke-Build

after_build:
- ps: Invoke-CopyOutput

on_success:
- ps: Invoke-NugetCheck

artifacts:
  - path: build
    name: build-folder
    type: zip
