version: 6.7.0.{build}
image: Visual Studio 2015
configuration: Release
deploy: off

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore src\Stripe.sln

build:
  project: src\Stripe.sln
  verbosity: minimal

after_build:
- cmd: 'build.bat'

artifacts:
- path: build
- path: src
- path: '**'
  name: Stripe.net
