version: 6.7.0.{build}
image: Visual Studio 2015
deploy: off

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore src\Stripe.sln

build:
  project: src\Stripe.sln
  publish_nuget: true
  verbosity: minimal

artifacts:
- path: .
  name: Stripe

on_finish:
- cmd: type build\Stripe.net.nuspec
